### ISSUE TITLE
[FEAT] Add footer

### ISSUE THREAD

**Issue by prnvtripathi** [LetsSpeakUp/website#8]
create a component, which is a footer

**Comment by himanshu1221** [comment]
Can you share some design it would be much easier to start working on

**Comment by prnvtripathi** [comment]
The ui for whole website is here :
https://letsspeakup.my.canva.site/

**Comment by prnvtripathi** [comment]
@himanshu1221 I've completed this issue, can you check another one.

**Comment by himanshu1221** [comment]
> @himanshu1221 I've completed this issue, can you check another one.

Sure it just slipped from my mind sorry for the delay I'll surely look into another one
